version: 0.2
env:
  variables:
    NODE_OPTIONS: "--max-old-space-size=252400"
    CACHE_CONTROL: "252400"
    APP_NAME: "trevauty-external"
    S3_BUCKET: "arn:aws:s3:::vendeur-hub-dashboard"
    BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - echo install process started
      - npm install
  pre_build:
    commands:
      - echo installing dependencies...
  build:
    commands:
      - echo build process started now
      - npm run build -- --configuration=production
      - echo Finished the build project
  post_build:
    commands:
      - echo publish app...
      # - aws s3 cp s3://vendeur-hub-dashboard/Procfile ./dist 
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
artifacts:
  files:
    - '**/*'
  base-directory: './'